added checks for the not-deprecated linking flags on OSX; disabled altivec on x86_64 machines
git-svn-id: https://pd-gem.svn.sourceforge.net/svnroot/pd-gem/trunk/Gem@2001 49b2a0ca-c541-4d49-a7ef-d785e4371512

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -15991,7 +15991,7 @@ fi
 # that don't support it
 # why? think cross-compilation
 
-if test "x${ARCH}" = "xi386" || test "x${ARCH}" = "xi686"; then
+if test "x${ARCH}" = "xi386" || test "x${ARCH}" = "xi686" || test "x${ARCH}" = "xx86_64"; then
  if test "x$enable_altivec" != "xyes"; then enable_altivec="no"; fi
 fi
 
@@ -16149,6 +16149,80 @@ echo "${ECHO_T}no" >&6; }
 
 # linking on os-X
 
+  { echo "$as_me:$LINENO: checking whether linker accepts \"-dynamiclib -mmacosx-version-min=10.3 -undefined dynamic_lookup\"" >&5
+echo $ECHO_N "checking whether linker accepts \"-dynamiclib -mmacosx-version-min=10.3 -undefined dynamic_lookup\"... $ECHO_C" >&6; }
+  gem_check_ldflags_org="${LDFLAGS}"
+  LDFLAGS="-dynamiclib -mmacosx-version-min=10.3 -undefined dynamic_lookup ${LDFLAGS}"
+
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  gem_check_ldflags_success="yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	gem_check_ldflags_success="no"
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+  if test "x$gem_check_ldflags_success" = "xyes"; then
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+  else
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+    LDFLAGS="$gem_check_ldflags_org"
+
   { echo "$as_me:$LINENO: checking whether linker accepts \"-bundle -undefined suppress -flat_namespace\"" >&5
 echo $ECHO_N "checking whether linker accepts \"-bundle -undefined suppress -flat_namespace\"... $ECHO_C" >&6; }
   gem_check_ldflags_org="${LDFLAGS}"
@@ -16222,6 +16296,9 @@ echo "${ECHO_T}yes" >&6; }
     { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
     LDFLAGS="$gem_check_ldflags_org"
+
+  fi
+
 
   fi
 
